services:
  - type: web
    name: quick-care-hospital
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hospital_project.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: quick-care-db
          property: connectionString
    autoDeploy: true

databases:
  - name: quick-care-db
    plan: free
