# Generated by Django 5.2.1 on 2025-05-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
    ]
